# Generated by Django 4.1 on 2022-08-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Enter your name')),
                ('surname', models.CharField(max_length=50, verbose_name='Enter your surname')),
                ('telephone_number', models.CharField(max_length=50, verbose_name='Enter your telephone number')),
                ('title', models.CharField(max_length=50, verbose_name='Enter title')),
                ('description', models.TextField(verbose_name='Enter description')),
                ('city', models.CharField(max_length=50, verbose_name='Enter city, you live')),
                ('key_help_words', models.CharField(max_length=50, verbose_name='Enter key words')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
