# Generated by Django 4.1 on 2022-08-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='telephone_number',
            field=models.IntegerField(blank=True, help_text='Enter your telephone number'),
        ),
    ]
