# Generated by Django 4.1 on 2022-08-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0003_remove_post_key_help_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.TextField(max_length=50, verbose_name='Enter city, you live'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Enter your name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='surname',
            field=models.TextField(max_length=50, verbose_name='Enter your surname'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=50, verbose_name='Enter title'),
        ),
    ]
