# Generated by Django 4.1 on 2022-08-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0004_alter_post_city_alter_post_name_alter_post_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(max_length=50, unique=True, verbose_name='Enter your name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='surname',
            field=models.TextField(max_length=50, unique=True, verbose_name='Enter your surname'),
        ),
        migrations.AlterField(
            model_name='post',
            name='telephone_number',
            field=models.IntegerField(blank=True, help_text='Enter your telephone number', unique=True),
        ),
    ]
