# Generated by Django 4.1 on 2022-08-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0005_alter_post_name_alter_post_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Enter your name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='surname',
            field=models.TextField(max_length=50, verbose_name='Enter your surname'),
        ),
    ]
